version: '3'
services:
  backend-app:
    build:
      context: ./backend/
    ports:
      - "8080:8080"
    environment:
      DB_HOST: 172.18.0.1
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5455
        #    depends_on:
        #- postgres-db

  frontend-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:12
    container_name: myPostgresDb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
